---
- hosts: all
  become: true
  tasks:
    - name: Enable Repo
      yum_repository:
        name: 'kubernetes'
        description: 'Kubernetes'
        baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
        gpgcheck: yes
        sslverify: yes
        gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    - name: Install Packages
      yum:
        name: "{{ item }}"
      with_items:
        - docker
        - kubelet
        - kubeadm
        - kubectl
    - name: SELinux
      selinux:
        policy: targeted
        state: permissive
        #    - name: Sysctl Conf
        #      sysctl:
        #        name: "{{ item }}"
        #        value: 1
        #        sysctl_set: yes
        #        state: present
        #        reload: yes
        #        sysctl_file: /etc/sysctl.conf
        #      with_items:
        #      - net.bridge.bridge-nf-call-ip6tables
        #      - net.bridge.bridge-nf-call-iptables
    - name: Services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - docker
        - kubelet

